version: "3.8"

services:
  cmc-booking-room:
    image: ghcr.io/${GITHUB_REPOSITORY:-your-username/cmc-bookinh-room-v6}:main
    ports:
      - "3000:80"
    container_name: cmc-booking-room-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
